# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PhotoGalleryMaker.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackPage1 = QtWidgets.QWidget()
        self.stackPage1.setObjectName("stackPage1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.stackPage1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.appName = QtWidgets.QLabel(self.stackPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appName.sizePolicy().hasHeightForWidth())
        self.appName.setSizePolicy(sizePolicy)
        self.appName.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.appName.setBaseSize(QtCore.QSize(2000, 3000))
        self.appName.setObjectName("appName")
        self.verticalLayout_2.addWidget(self.appName)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(-1, 30, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.writeKeyword = QtWidgets.QLineEdit(self.stackPage1)
        self.writeKeyword.setObjectName("writeKeyword")
        self.horizontalLayout.addWidget(self.writeKeyword)
        self.enterButton = QtWidgets.QPushButton(self.stackPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enterButton.sizePolicy().hasHeightForWidth())
        self.enterButton.setSizePolicy(sizePolicy)
        self.enterButton.setMaximumSize(QtCore.QSize(100, 30))
        self.enterButton.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.enterButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.enterButton.setObjectName("enterButton")
        self.horizontalLayout.addWidget(self.enterButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.stackPage1)
        self.stackPage2 = QtWidgets.QWidget()
        self.stackPage2.setObjectName("stackPage2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.stackPage2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.zdjecie = QtWidgets.QLabel(self.stackPage2)
        self.zdjecie.setText("")
        self.zdjecie.setScaledContents(True)
        self.zdjecie.setObjectName("zdjecie")
        self.verticalLayout_3.addWidget(self.zdjecie)
        self.stackedWidget.addWidget(self.stackPage2)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PhotoGallery Maker"))
        self.appName.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Welcome to </span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">PHOTOGALLERY MAKER</span></p></body></html>"))
        self.writeKeyword.setPlaceholderText(_translate("MainWindow", "Type what you want to see"))
        self.enterButton.setText(_translate("MainWindow", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
